name: 'Build Jekyll'
description: 'Local pipeline build of Jekyll content; follow-on actions must publish it somewhere'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'book-open'
  color: 'white'
inputs:
  jekyll-config:
    description: Jekyll _config.yml files to build with
    required: false
    default: "_config.yml"
